
const NOMINATIM = "https://nominatim.openstreetmap.org";
const OSRM = "https://router.project-osrm.org";
const OVERPASS = "https://overpass-api.de/api/interpreter";
export const RAPIDO_CITY_DATASET = ["Coimbatore","Chennai","Bengaluru","Hyderabad","Mumbai","Delhi","Pune","Madurai","Salem","Trichy","Erode","Tiruppur","Mysuru","Kochi","Vijayawada","Visakhapatnam","Jaipur","Kolkata","Ahmedabad"];
export const FAMOUS_PLACE_HINTS = {ooty:["Botanical Garden","Ooty Lake","Doddabetta Peak","Rose Garden","Pykara Lake","Tea Factory"],coimbatore:["Marudhamalai Temple","VOC Park","Gedee Car Museum","Isha Yoga Center","Brookefields Mall"],chennai:["Marina Beach","Kapaleeshwarar Temple","Fort St George","Valluvar Kottam","Besant Nagar Beach"],salem:["Yercaud","1008 Lingam Temple","Kiliyur Falls","Mettur Dam","Kurumbapatti Zoological Park"],madurai:["Meenakshi Amman Temple","Thirumalai Nayakkar Palace","Gandhi Museum","Alagar Kovil"],bengaluru:["Lalbagh","Cubbon Park","Bangalore Palace","ISKCON Temple","UB City"]};
export async function geocodePlace(query){if(!query||query.trim().length<2)return[];const url=`${NOMINATIM}/search?format=jsonv2&limit=8&countrycodes=in&q=${encodeURIComponent(query)}`;const r=await fetch(url,{headers:{"Accept-Language":"en"}});if(!r.ok)throw new Error("Place search failed");const data=await r.json();return data.map(i=>({name:i.display_name,shortName:i.name||i.display_name.split(",")[0],lat:Number(i.lat),lon:Number(i.lon),type:i.type||i.class||"place"}));}
export async function getRoute(start,end,profile="driving"){const url=`${OSRM}/route/v1/${profile}/${start.lon},${start.lat};${end.lon},${end.lat}?overview=full&geometries=geojson&steps=true&alternatives=true`;const r=await fetch(url);if(!r.ok)throw new Error("Route service failed");const d=await r.json();if(d.code!=="Ok")throw new Error("Route not found");return d.routes.map((route,index)=>({id:`route-${index}`,distanceKm:route.distance/1000,durationMin:route.duration/60,coordinates:route.geometry.coordinates.map(([lon,lat])=>[lat,lon]),steps:route.legs.flatMap(leg=>leg.steps||[])}));}
export async function getWeather(lat,lon){const url=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,relative_humidity_2m,precipitation,weather_code,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=auto`;const r=await fetch(url);if(!r.ok)throw new Error("Weather failed");return r.json();}
async function overpass(q){const r=await fetch(OVERPASS,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded;charset=UTF-8"},body:`data=${encodeURIComponent(q)}`});if(!r.ok)throw new Error("Overpass failed");return r.json();}
export async function getNearbyPlaces(lat,lon,type="food",radius=10000){const filters={food:'["amenity"~"restaurant|cafe|fast_food|food_court"]',rest:'["amenity"~"toilets|drinking_water|fuel|parking"]',attraction:'["tourism"~"attraction|museum|viewpoint|gallery|zoo|theme_park"]',hospital:'["amenity"="hospital"]',police:'["amenity"="police"]',bus:'["highway"="bus_stop"]',hotel:'["tourism"~"hotel|guest_house|hostel"]'};const filter=filters[type]||filters.food;const q=`[out:json][timeout:25];(node${filter}(around:${radius},${lat},${lon});way${filter}(around:${radius},${lat},${lon});relation${filter}(around:${radius},${lat},${lon}););out center tags 35;`;const data=await overpass(q);return(data.elements||[]).map(el=>{const tags=el.tags||{};const itemLat=el.lat??el.center?.lat;const itemLon=el.lon??el.center?.lon;return{id:`${el.type}-${el.id}`,name:tags.name||tags["name:en"]||readable(tags.amenity||tags.tourism||tags.highway||"Place"),lat:itemLat,lon:itemLon,category:tags.amenity||tags.tourism||tags.highway||tags.leisure||type,road:tags["addr:street"]||tags.local_ref||"Road not listed",cuisine:tags.cuisine||"",openingHours:tags.opening_hours||"Timing not listed",phone:tags.phone||tags["contact:phone"]||""}}).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon));}
function readable(v=""){return String(v).split("_").map(w=>w?w[0].toUpperCase()+w.slice(1):w).join(" ");}
export function buildFareOptions(distanceKm,durationMin,mode,startName="",endName=""){const cityText=`${startName} ${endName}`.toLowerCase();const rapidoAvailable=RAPIDO_CITY_DATASET.some(city=>cityText.includes(city.toLowerCase()));const rules=[{provider:"Walk",vehicle:"Walking",base:0,perKm:0,speed:4.5,icon:"🚶",available:distanceKm<=5},{provider:"Local Bus",vehicle:"Bus",base:12,perKm:1.35,speed:27,icon:"🚌",available:true},{provider:"Train Estimate",vehicle:"Train",base:35,perKm:.85,speed:55,icon:"🚆",available:distanceKm>12},{provider:"Rapido Estimate",vehicle:"Bike Taxi",base:28,perKm:8.5,speed:34,icon:"🏍️",available:rapidoAvailable},{provider:"Auto Estimate",vehicle:"Auto",base:40,perKm:15,speed:28,icon:"🛺",available:distanceKm<45},{provider:"Ola Estimate",vehicle:"Cab",base:75,perKm:17.5,speed:38,icon:"🚕",available:true},{provider:"Uber Estimate",vehicle:"Cab",base:85,perKm:18.5,speed:40,icon:"🚖",available:true}];const filtered=rules.filter(rule=>{if(!rule.available)return false;if(mode==="college"||mode==="budget")return["Walking","Bus","Train","Bike Taxi"].includes(rule.vehicle);if(mode==="office")return["Bike Taxi","Auto","Cab","Bus"].includes(rule.vehicle);if(mode==="family")return["Cab","Train","Bus"].includes(rule.vehicle);if(mode==="medical")return["Cab","Auto"].includes(rule.vehicle);return true});return filtered.map(rule=>{const fare=Math.round(rule.base+distanceKm*rule.perKm);const minutes=rule.vehicle==="Cab"?Math.round(durationMin):Math.round((distanceKm/rule.speed)*60);return{...rule,fare,minutes:Math.max(1,minutes),note:rule.provider.includes("Estimate")?"Estimated fare. Confirm in provider app.":"Route-based estimate."}}).sort((a,b)=>a.fare-b.fare);}
export function generateTourPlan(places,budget,weather){const budgetNumber=Number(budget)||1500;const perPlace=Math.max(100,Math.floor(budgetNumber/Math.max(1,Math.min(places.length,5))));return places.slice(0,6).map((place,index)=>{const hour=9+Math.floor(index*1.5);const minute=index%2?"30":"00";const spend=index===0?Math.max(0,perPlace-50):perPlace;const rainChance=weather?.daily?.precipitation_probability_max?.[0]||0;return{...place,time:`${String(hour).padStart(2,"0")}:${minute}`,spend,reason:rainChance>50?"Indoor/nearby option preferred due to rain chance":"Popular nearby place for this destination"}});}
export function famousHints(destinationText){const key=Object.keys(FAMOUS_PLACE_HINTS).find(k=>destinationText.toLowerCase().includes(k));return key?FAMOUS_PLACE_HINTS[key]:["Famous viewpoint","Local market","Popular temple","Museum","Food street"]}
